{{- if .Values.envVariables -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clapp.fullname" . }}-env
  labels:
    {{- include "clapp.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envVariables }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
