{{- if .Values.payloadcms.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-migrate
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-migrator
          image: "{{ .Values.payloadcms.migrator.image }}:{{ .Values.payloadcms.migrator.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            {{- if .Values.envVariables }}
            - configMapRef:
                name: {{ include "clapp.fullname" . }}-env
            {{- end }}
          {{- if .Values.postgres.enabled }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.serviceName }}-app
                  key: fqdn-uri
          {{- end }}
          # The image has a default CMD to run migrations; override if needed
          # command: ["sh", "-lc", "PAYLOAD_CONFIG_PATH=src/payload.config.ts node node_modules/payload/bin.js migrate"]
{{- end }}
